### ISSUE TITLE
Explicit treap ensure-key inconsistent work.

### ISSUE THREAD

**Issue by commander-trashdin** [privet-kitty/cl-competitive#3]
Say we have a treap-1 of ((0 . 0)) and a treap-2 of ((0 . 3) (1 . 1) (5 . 5)).
Doing this:
```
(treap-map
     (lambda (key value)
       (treap-ensure-key treap-1
                         key (- value)))
     treap-2)
```
sometimes fills treap-1 with key, negated value (all of them) sometimes only with part of them, and it's completely random. It seems that it's always puts (0 . -3) in there, but other may or may not be there.

**Comment by privet-kitty** [comment]
You need to do

```lisp
(treap-map
     (lambda (key value)
       (setq treap-1 (treap-ensure-key treap-1 key (- value))))
     treap-2)
```

instead. (Just the same as destructive operations to cons, like `delete`  or `sort`)

**Comment by commander-trashdin** [comment]
Got it, thanks. 

I am planning on writing RB tree and also (one of my beginner friends l) writes suffix automaton. Would you be interested in this contributions?
