### ISSUE TITLE
where to practice competitive programming in common-lisp?

### ISSUE THREAD

**Issue by smvamse** [privet-kitty/cl-competitive#4]
As far as I know, only code-chef and spoj support common-lisp.
And both of them return `NZEC`, when I submit solutions in common-lisp.
Any suggestions?

**Comment by privet-kitty** [comment]
Hi.

- By far the best quality site for competitive programming at which you can use Common Lisp is AtCoder. It provides most problems from rated contests in English. A drawback is, however,  that no English editorial is provided for beginner contests. Other famous and international sites include CodeChef, CS Academy, HackerRank, HackerEarth, and Kattis.
- You can see other people's submissions in most sites. (Exceptions include Kattis.)
- Most sites provide an online test environment: e.g. [here](https://www.codechef.com/ide?itm_medium=navmenu&itm_campaign=ide) at CodeChef.

**Comment by smvamse** [comment]
Thanks

**Comment by smvamse** [comment]
Thanks
